### ISSUE TITLE
Request: Crop right-click compatibility

### ISSUE THREAD

**Issue by xeronut** [tterrag1098/ttCore#14]
Hello!  I love being able to right-click crops to harvest and replant, and I noted in your config the ability to add in modded crops depending on implementation.  The mod 'Lots Of Food' - http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1282670-lots-of-food-1-7-10-v6 - does not seem to want to work with this option, and I was wondering if specific implementation was a possibility.  Thank you for your time.

**Comment by tterrag1098** [comment]
Fixed via f9c165418cc610b599b89a0ec03cecffdafdf23f
