### ISSUE TITLE
ttCore-MC1.7.10-0.1.0-62 crashes Dedicated server

### ISSUE THREAD

**Issue by psychofad** [tterrag1098/ttCore#17]
It appears that ttcore is trying to run client side code on the server in build 62.  

Crashlog:
http://pastebin.com/UngRuMan

**Comment by tterrag1098** [comment]
Whoops! One moment.

**Comment by tterrag1098** [comment]
Fixed via https://github.com/tterrag1098/ttCore/commit/137fa3823d9f98a24dfd44f9bdbee2a37ad4b1f6
