### ISSUE TITLE
expboost crash

### ISSUE THREAD

**Issue by Frontrider** [tterrag1098/ttCore#23]
https://www.dropbox.com/s/3gveslpckqf43mr/crash-2015-03-28_18.28.26-server.txt?dl=0#

**Comment by tterrag1098** [comment]
You are extremely out of date

**Comment by Frontrider** [comment]
still persist after updating.

**Comment by tterrag1098** [comment]
What were you doing when this occurred? I see no way the mentioned line of code can crash unless something is seriously wrong.

**Comment by tterrag1098** [comment]
Wait I think I see it, are you shooting arrows at entities with, say, a dispenser? Or any kind of automated arrow shooting device?

**Comment by tterrag1098** [comment]
Even then, it would have to be shot with a bow with XP Boost on it, so I'm still pretty confused.

**Comment by Frontrider** [comment]
got back to my computer: They are having flux infused bows.
