### ISSUE TITLE
Crash on client load

### ISSUE THREAD

**Issue by PsionicArchon** [tterrag1098/ttCore#27]
I'm not sure if this is ttcore or Super Massive Tech related. Something about config generation is mentioned.

Crash: http://pastebin.com/RTayQa6S

I am using the latest versions available for both mods. I've tried both old and newer versions of forge, settling with 10.13.2.1352 (Logistics Pipes compatibility).

**Comment by tterrag1098** [comment]
Yeah, I made a small mistake and that version of ttCore (and any newer ones) will not be backwards compatible. This is somewhat intentional as I am starting development on ttCore 0.2 now. For now, just use the previous ttCore version.
