### ISSUE TITLE
Crash with Cauldron & Minechem

### ISSUE THREAD

**Issue by Amaxter** [tterrag1098/ttCore#33]
Using ttCore 0.1.1-76 I've confirmed that I get the following crash on a server with Cauldron 1403 when using ttCore and Minechem: http://hastebin.com/mopivevabe.profile

**Comment by tterrag1098** [comment]
Enchantment id conflict, change the configs.

**Comment by Amaxter** [comment]
It's not that simple unfortunately. Minechem doesn't have configurable enchantment id's but alone it works fine, when I add ttCore it crashes like that.

**Comment by tterrag1098** [comment]
ttCore does have configs for its ids though
