### ISSUE TITLE
Crash when mining DenseOre with Auto-Smelt pickaxe

### ISSUE THREAD

**Issue by mystise** [tterrag1098/ttCore#34]
Crashlog: http://pastebin.com/t4A5suht

Forge: 10.13.4.1448-1.7.10
Dense Ores: 1.6.2
ttCore: 0.1.1-77

In the test, I used a dense iron ore and a newly made diamond pickaxe with auto-smelt 1 on it.

**Comment by tterrag1098** [comment]
Fixed under #36
