### ISSUE TITLE
[REQUEST] Set "supderduper fun mode" false for default

### ISSUE THREAD

**Issue by jawsawn** [tterrag1098/ttCore#37]
For love of god please...
MAY HAVE MERCY
Tired of turning it off. Agonizes me more than fun.

**Comment by tterrag1098** [comment]
I don't get what the big deal is. You can even turn it off from ingame with the mod options menu, takes about 20 seconds. Most people enjoy it.

**Comment by jawsawn** [comment]
It makes lag

**Comment by tterrag1098** [comment]
Fireworks can cause FPS lag on some systems, anything with a lot of particles will. If your computer can't handle it, turn it off, most can. Again it's not hard.

**Comment by jawsawn** [comment]
Its just so sudden.

Its just like 1.8 achivements. Feels nice at start but get annoying
