### ISSUE TITLE
[0.1.1] Right click crop handler should return if length of data is not 4 (instead of 3)

### ISSUE THREAD

**Issue by TheElementalOfDestruction** [tterrag1098/ttCore#38]
On [line 26 of IMCRightClickCrop.java](https://github.com/tterrag1098/ttCore/blob/0.1.1/src/main/java/tterrag/core/common/imc/handlers/IMCRightClickCrop.java#L26) length of data should cause the program to return if it is not 4. Currently it is set to do this if it is not 3, but a [later line](https://github.com/tterrag1098/ttCore/blob/0.1.1/src/main/java/tterrag/core/common/imc/handlers/IMCRightClickCrop.java#L31) tries to use `data[3]` which means data would have to have a length of 4.

**Comment by tterrag1098** [comment]
This mod hasn't been supported for years.
